In [6]:
!pip install scikit-learn

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

steps = [
    ("standard_scaler", StandardScaler()),
    ("classifier", LogisticRegression())
]
steps


[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [9]:
pipe = Pipeline(steps)

In [10]:
# visualize 
from sklearn import set_config
set_config(display = "diagram")
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [12]:
# creating a dataset 
from sklearn.datasets import make_classification
X,y = make_classification(n_samples = 1000)
X.shape

(1000, 20)

In [14]:
from sklearn.model_selection import train_test_split
X_train ,X_test , y_train  ,y_test = train_test_split(X,y ,test_size =0.33 ,random_state = 42)
X_train

array([[ 0.50461937, -2.3552924 , -1.28970164, ...,  0.64055609,
        -1.29594757, -0.11891869],
       [ 0.00677519,  0.74853073,  0.26619633, ..., -1.14867324,
        -0.34589972,  1.23181322],
       [-0.62749848,  1.27448958, -0.61258795, ...,  0.0690846 ,
        -1.99479484, -0.21722636],
       ...,
       [-0.64464345,  0.26630625, -0.59406364, ...,  0.94373554,
         0.17706662,  0.48077623],
       [ 0.99786044, -0.65309575, -0.87957084, ...,  2.07154675,
        -0.0925156 ,  0.36742978],
       [ 1.52637396, -1.27450589, -0.45350584, ...,  1.55989943,
         1.06136401, -0.80718003]])

In [15]:
pipe.fit(X_train , y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [16]:
y_pred = pipe.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [ ]:
## ex 2
### displaying a pipeline with standard scalar , dim reduction , 


In [28]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [29]:
steps = [
    ("scaling", StandardScaler()),
    ("PCA", PCA(n_components=3)),
    ("SVC", SVC())
]

pipe2 = Pipeline(steps)

In [31]:
pipe2.predict(X_test)

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,

In [ ]:
# complex ex of col transformers

In [36]:
from sklearn.impute import SimpleImputer
import numpy as np

In [37]:
numeric_processor = Pipeline(
    steps=[
        ("imputation_mean", SimpleImputer(missing_values=np.nan, strategy="mean")),
        ("scaler", StandardScaler())
    ]
)

numeric_processor                                          

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [40]:
# cateogical processing pipe line 
from sklearn.preprocessing import OneHotEncoder 

In [41]:
categorical_processor = Pipeline(
    steps = [("imputation_consatnt",SimpleImputer(fill_value = "missing" , strategy = "constant"))
             ,("onehot",OneHotEncoder(handle_unknown = "ignore"))]
)
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [42]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
    [("categorical" , categorical_processor,["gender","city"]),
     ("numberical",numeric_processor,["age","height"])]
)
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numberical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [43]:
from sklearn.pipeline import make_pipeline 

In [44]:
pipe = make_pipeline(preprocessor , LogisticRegression())
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numberical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])